"""add pending profile fields to users

Revision ID: 22c21b981aeb
Revises: a32ee7f32c35
Create Date: 2026-09-14 15:12:30.183053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c21b981aeb'
down_revision: Union[str, Sequence[str], None] = 'a32ee7f32c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('specialization', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('license_number', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'position')
    op.drop_column('users', 'license_number')
    op.drop_column('users', 'specialization')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
